#- name: Installing nginx
#  ansible.builtin.dnf:
#    name: nginx
#    state: present

#- name: Copy Expense Configuration
#  ansible.builtin.template:
#    src: expense.conf
#    dest: /etc/nginx/default.d/expense.conf

#- name: Import Common role - App Pre-requisites
#  ansible.builtin.import_role:
#    name: common
#    tasks_from: app-prereq
#  vars:
#    app_dir: /usr/share/nginx/html
#    component: frontend

#- name: Starting nginx Service
#  ansible.builtin.systemd:
#    name: nginx
#    state: restarted
#    enabled: yes

#- name: Import ELX Role - Filebeat
#  ansible.builtin.import_role:
#    name: elk
#    tasks_from: filebeat

#- name: Import Prometheus - Node Exporter
#  ansible.builtin.import_role:
#    name: prometheus
#    tasks_from: node-exporter

#- name: Import Grafana - Dashboard Creation
#  ansible.builtin.import_role:
#    name: grafana

#- name: Import prometheus Role - Alert Rules Update
#  ansible.builtin.import_role:
#    name: prometheus
#    tasks_from: alert-rules-update


- name: Install New Relic agent
  ansible.builtin.shell: curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash && sudo NEW_RELIC_API_KEY=NRAK-57BLDGZ33LH9F67A2EZAPV56EMX NEW_RELIC_ACCOUNT_ID=4254570 /usr/local/bin/newrelic install -y -n infrastructure-agent-installer